{
  description = "NixOS Flake Configuration";

  # The 'inputs' are where your software comes from
  inputs = {
    # Using the unstable branch for the absolute latest GNOME and app updates
    nixpkgs.url = "github:nixos/nixpkgs/nixos-25.11"; 
    
    # The official hardware profile repository
    nixos-hardware.url = "github:NixOS/nixos-hardware/master";
  };

  # The 'outputs' build your specific system
  outputs = { self, nixpkgs, nixos-hardware, ... }@inputs: {
    nixosConfigurations = {
      # thinkpad-e470 profile: sudo nixos-rebuild switch --flake .#thinkpad-e470
      thinkpad-e470 = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        
        # This passes the inputs down to your configuration.nix
        specialArgs = { inherit inputs; }; 
        
        modules = [
          # 1. Apply the ThinkPad E470 battery, trackpad, and CPU fixes
          nixos-hardware.nixosModules.lenovo-thinkpad-e470
          nixos-hardware.nixosModules.common-gpu-nvidia-disable
          
          # 2. Include the partition layout generated by the Calamares installer
          ./hardware-configuration.nix
          
          # 3. Include your personal setup
          ./configuration.nix
        ];
      };
    };
  };
}
